/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const InspectionStatus = IDL.Variant({
  'completed' : IDL.Null,
  'draft' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Time = IDL.Int;
export const CheckItemStatus = IDL.Variant({
  'na' : IDL.Null,
  'fail' : IDL.Null,
  'pass' : IDL.Null,
});
export const InspectionCategory = IDL.Variant({
  'fluid' : IDL.Null,
  'tires' : IDL.Null,
  'brakes' : IDL.Null,
  'interior' : IDL.Null,
  'body' : IDL.Null,
  'lights' : IDL.Null,
  'engine' : IDL.Null,
});
export const InspectionChecklistItem = IDL.Record({
  'status' : CheckItemStatus,
  'item' : IDL.Text,
  'notes' : IDL.Text,
  'category' : InspectionCategory,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PhotoCategory = IDL.Variant({
  'front' : IDL.Null,
  'damage' : IDL.Null,
  'rear' : IDL.Null,
  'side' : IDL.Null,
});
export const PhotoReference = IDL.Record({
  'blob' : ExternalBlob,
  'caption' : IDL.Text,
  'category' : PhotoCategory,
});
export const Inspection = IDL.Record({
  'status' : InspectionStatus,
  'date' : Time,
  'checklistItems' : IDL.Vec(InspectionChecklistItem),
  'notes' : IDL.Text,
  'inspectionId' : IDL.Text,
  'overallStatus' : CheckItemStatus,
  'photos' : IDL.Vec(PhotoReference),
  'vehicleId' : IDL.Text,
  'inspector' : IDL.Principal,
});
export const Vehicle = IDL.Record({
  'vin' : IDL.Text,
  'model' : IDL.Text,
  'licensePlate' : IDL.Text,
  'owner' : IDL.Principal,
  'make' : IDL.Text,
  'color' : IDL.Text,
  'year' : IDL.Nat16,
  'odometer' : IDL.Nat32,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInspection' : IDL.Func([Inspection], [], []),
  'addOrUpdateVehicle' : IDL.Func([Vehicle], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteVehicle' : IDL.Func([IDL.Text], [], []),
  'getAllInspections' : IDL.Func([], [IDL.Vec(Inspection)], ['query']),
  'getAllVehiclesByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Vehicle)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInspection' : IDL.Func([IDL.Text], [IDL.Opt(Inspection)], ['query']),
  'getInspectionsForVehicleOverTime' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Int],
      [IDL.Vec(Inspection)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVehicle' : IDL.Func([IDL.Text], [IDL.Opt(Vehicle)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listInspectionsByInspector' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Inspection)],
      ['query'],
    ),
  'listInspectionsByStatus' : IDL.Func(
      [InspectionStatus],
      [IDL.Vec(Inspection)],
      ['query'],
    ),
  'listInspectionsByVehicle' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Inspection)],
      ['query'],
    ),
  'listVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const InspectionStatus = IDL.Variant({
    'completed' : IDL.Null,
    'draft' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Time = IDL.Int;
  const CheckItemStatus = IDL.Variant({
    'na' : IDL.Null,
    'fail' : IDL.Null,
    'pass' : IDL.Null,
  });
  const InspectionCategory = IDL.Variant({
    'fluid' : IDL.Null,
    'tires' : IDL.Null,
    'brakes' : IDL.Null,
    'interior' : IDL.Null,
    'body' : IDL.Null,
    'lights' : IDL.Null,
    'engine' : IDL.Null,
  });
  const InspectionChecklistItem = IDL.Record({
    'status' : CheckItemStatus,
    'item' : IDL.Text,
    'notes' : IDL.Text,
    'category' : InspectionCategory,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PhotoCategory = IDL.Variant({
    'front' : IDL.Null,
    'damage' : IDL.Null,
    'rear' : IDL.Null,
    'side' : IDL.Null,
  });
  const PhotoReference = IDL.Record({
    'blob' : ExternalBlob,
    'caption' : IDL.Text,
    'category' : PhotoCategory,
  });
  const Inspection = IDL.Record({
    'status' : InspectionStatus,
    'date' : Time,
    'checklistItems' : IDL.Vec(InspectionChecklistItem),
    'notes' : IDL.Text,
    'inspectionId' : IDL.Text,
    'overallStatus' : CheckItemStatus,
    'photos' : IDL.Vec(PhotoReference),
    'vehicleId' : IDL.Text,
    'inspector' : IDL.Principal,
  });
  const Vehicle = IDL.Record({
    'vin' : IDL.Text,
    'model' : IDL.Text,
    'licensePlate' : IDL.Text,
    'owner' : IDL.Principal,
    'make' : IDL.Text,
    'color' : IDL.Text,
    'year' : IDL.Nat16,
    'odometer' : IDL.Nat32,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInspection' : IDL.Func([Inspection], [], []),
    'addOrUpdateVehicle' : IDL.Func([Vehicle], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteVehicle' : IDL.Func([IDL.Text], [], []),
    'getAllInspections' : IDL.Func([], [IDL.Vec(Inspection)], ['query']),
    'getAllVehiclesByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Vehicle)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInspection' : IDL.Func([IDL.Text], [IDL.Opt(Inspection)], ['query']),
    'getInspectionsForVehicleOverTime' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Int],
        [IDL.Vec(Inspection)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVehicle' : IDL.Func([IDL.Text], [IDL.Opt(Vehicle)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listInspectionsByInspector' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Inspection)],
        ['query'],
      ),
    'listInspectionsByStatus' : IDL.Func(
        [InspectionStatus],
        [IDL.Vec(Inspection)],
        ['query'],
      ),
    'listInspectionsByVehicle' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Inspection)],
        ['query'],
      ),
    'listVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };