/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CheckItemStatus = { 'na' : null } |
  { 'fail' : null } |
  { 'pass' : null };
export type ExternalBlob = Uint8Array;
export interface Inspection {
  'status' : InspectionStatus,
  'date' : Time,
  'checklistItems' : Array<InspectionChecklistItem>,
  'notes' : string,
  'inspectionId' : string,
  'overallStatus' : CheckItemStatus,
  'photos' : Array<PhotoReference>,
  'vehicleId' : string,
  'inspector' : Principal,
}
export type InspectionCategory = { 'fluid' : null } |
  { 'tires' : null } |
  { 'brakes' : null } |
  { 'interior' : null } |
  { 'body' : null } |
  { 'lights' : null } |
  { 'engine' : null };
export interface InspectionChecklistItem {
  'status' : CheckItemStatus,
  'item' : string,
  'notes' : string,
  'category' : InspectionCategory,
}
export type InspectionStatus = { 'completed' : null } |
  { 'draft' : null } |
  { 'inProgress' : null };
export type PhotoCategory = { 'front' : null } |
  { 'damage' : null } |
  { 'rear' : null } |
  { 'side' : null };
export interface PhotoReference {
  'blob' : ExternalBlob,
  'caption' : string,
  'category' : PhotoCategory,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vehicle {
  'vin' : string,
  'model' : string,
  'licensePlate' : string,
  'owner' : Principal,
  'make' : string,
  'color' : string,
  'year' : number,
  'odometer' : number,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInspection' : ActorMethod<[Inspection], undefined>,
  'addOrUpdateVehicle' : ActorMethod<[Vehicle], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteVehicle' : ActorMethod<[string], undefined>,
  'getAllInspections' : ActorMethod<[], Array<Inspection>>,
  'getAllVehiclesByOwner' : ActorMethod<[Principal], Array<Vehicle>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInspection' : ActorMethod<[string], [] | [Inspection]>,
  'getInspectionsForVehicleOverTime' : ActorMethod<
    [string, bigint, bigint],
    Array<Inspection>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVehicle' : ActorMethod<[string], [] | [Vehicle]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listInspectionsByInspector' : ActorMethod<[Principal], Array<Inspection>>,
  'listInspectionsByStatus' : ActorMethod<
    [InspectionStatus],
    Array<Inspection>
  >,
  'listInspectionsByVehicle' : ActorMethod<[string], Array<Inspection>>,
  'listVehicles' : ActorMethod<[], Array<Vehicle>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];