/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Inspection {
    status: InspectionStatus;
    date: Time;
    checklistItems: Array<InspectionChecklistItem>;
    notes: string;
    inspectionId: string;
    overallStatus: CheckItemStatus;
    photos: Array<PhotoReference>;
    vehicleId: string;
    inspector: Principal;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Vehicle {
    vin: string;
    model: string;
    licensePlate: string;
    owner: Principal;
    make: string;
    color: string;
    year: number;
    odometer: number;
}
export interface InspectionChecklistItem {
    status: CheckItemStatus;
    item: string;
    notes: string;
    category: InspectionCategory;
}
export interface PhotoReference {
    blob: ExternalBlob;
    caption: string;
    category: PhotoCategory;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum CheckItemStatus {
    na = "na",
    fail = "fail",
    pass = "pass"
}
export enum InspectionCategory {
    fluid = "fluid",
    tires = "tires",
    brakes = "brakes",
    interior = "interior",
    body = "body",
    lights = "lights",
    engine = "engine"
}
export enum InspectionStatus {
    completed = "completed",
    draft = "draft",
    inProgress = "inProgress"
}
export enum PhotoCategory {
    front = "front",
    damage = "damage",
    rear = "rear",
    side = "side"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addInspection(inspection: Inspection): Promise<void>;
    addOrUpdateVehicle(vehicle: Vehicle): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteVehicle(vin: string): Promise<void>;
    getAllInspections(): Promise<Array<Inspection>>;
    getAllVehiclesByOwner(owner: Principal): Promise<Array<Vehicle>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInspection(inspectionId: string): Promise<Inspection | null>;
    getInspectionsForVehicleOverTime(vehicleId: string, startDate: bigint, endDate: bigint): Promise<Array<Inspection>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVehicle(vin: string): Promise<Vehicle | null>;
    isCallerAdmin(): Promise<boolean>;
    listInspectionsByInspector(inspector: Principal): Promise<Array<Inspection>>;
    listInspectionsByStatus(status: InspectionStatus): Promise<Array<Inspection>>;
    listInspectionsByVehicle(vehicleId: string): Promise<Array<Inspection>>;
    listVehicles(): Promise<Array<Vehicle>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { CheckItemStatus as _CheckItemStatus, ExternalBlob as _ExternalBlob, Inspection as _Inspection, InspectionCategory as _InspectionCategory, InspectionChecklistItem as _InspectionChecklistItem, InspectionStatus as _InspectionStatus, PhotoCategory as _PhotoCategory, PhotoReference as _PhotoReference, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, Vehicle as _Vehicle, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addInspection(arg0: Inspection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInspection(await to_candid_Inspection_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInspection(await to_candid_Inspection_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addOrUpdateVehicle(arg0: Vehicle): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateVehicle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateVehicle(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n25(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n25(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteVehicle(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVehicle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVehicle(arg0);
            return result;
        }
    }
    async getAllInspections(): Promise<Array<Inspection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInspections();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInspections();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVehiclesByOwner(arg0: Principal): Promise<Array<Vehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVehiclesByOwner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVehiclesByOwner(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInspection(arg0: string): Promise<Inspection | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInspection(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInspection(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInspectionsForVehicleOverTime(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<Inspection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInspectionsForVehicleOverTime(arg0, arg1, arg2);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInspectionsForVehicleOverTime(arg0, arg1, arg2);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVehicle(arg0: string): Promise<Vehicle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVehicle(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVehicle(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listInspectionsByInspector(arg0: Principal): Promise<Array<Inspection>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInspectionsByInspector(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInspectionsByInspector(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async listInspectionsByStatus(arg0: InspectionStatus): Promise<Array<Inspection>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInspectionsByStatus(to_candid_InspectionStatus_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInspectionsByStatus(to_candid_InspectionStatus_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async listInspectionsByVehicle(arg0: string): Promise<Array<Inspection>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInspectionsByVehicle(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInspectionsByVehicle(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVehicles(): Promise<Array<Vehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVehicles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVehicles();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_CheckItemStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CheckItemStatus): CheckItemStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_InspectionCategory_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InspectionCategory): InspectionCategory {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_InspectionChecklistItem_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InspectionChecklistItem): InspectionChecklistItem {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_InspectionStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InspectionStatus): InspectionStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_Inspection_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inspection): Promise<Inspection> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_PhotoCategory_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PhotoCategory): PhotoCategory {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
async function from_candid_PhotoReference_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PhotoReference): Promise<PhotoReference> {
    return await from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Inspection]): Promise<Inspection | null> {
    return value.length === 0 ? null : await from_candid_Inspection_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Vehicle]): Vehicle | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _InspectionStatus;
    date: _Time;
    checklistItems: Array<_InspectionChecklistItem>;
    notes: string;
    inspectionId: string;
    overallStatus: _CheckItemStatus;
    photos: Array<_PhotoReference>;
    vehicleId: string;
    inspector: Principal;
}): Promise<{
    status: InspectionStatus;
    date: Time;
    checklistItems: Array<InspectionChecklistItem>;
    notes: string;
    inspectionId: string;
    overallStatus: CheckItemStatus;
    photos: Array<PhotoReference>;
    vehicleId: string;
    inspector: Principal;
}> {
    return {
        status: from_candid_InspectionStatus_n30(_uploadFile, _downloadFile, value.status),
        date: value.date,
        checklistItems: from_candid_vec_n32(_uploadFile, _downloadFile, value.checklistItems),
        notes: value.notes,
        inspectionId: value.inspectionId,
        overallStatus: from_candid_CheckItemStatus_n35(_uploadFile, _downloadFile, value.overallStatus),
        photos: await from_candid_vec_n39(_uploadFile, _downloadFile, value.photos),
        vehicleId: value.vehicleId,
        inspector: value.inspector
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _CheckItemStatus;
    item: string;
    notes: string;
    category: _InspectionCategory;
}): {
    status: CheckItemStatus;
    item: string;
    notes: string;
    category: InspectionCategory;
} {
    return {
        status: from_candid_CheckItemStatus_n35(_uploadFile, _downloadFile, value.status),
        item: value.item,
        notes: value.notes,
        category: from_candid_InspectionCategory_n37(_uploadFile, _downloadFile, value.category)
    };
}
async function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: _ExternalBlob;
    caption: string;
    category: _PhotoCategory;
}): Promise<{
    blob: ExternalBlob;
    caption: string;
    category: PhotoCategory;
}> {
    return {
        blob: await from_candid_ExternalBlob_n42(_uploadFile, _downloadFile, value.blob),
        caption: value.caption,
        category: from_candid_PhotoCategory_n43(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    draft: null;
} | {
    inProgress: null;
}): InspectionStatus {
    return "completed" in value ? InspectionStatus.completed : "draft" in value ? InspectionStatus.draft : "inProgress" in value ? InspectionStatus.inProgress : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    na: null;
} | {
    fail: null;
} | {
    pass: null;
}): CheckItemStatus {
    return "na" in value ? CheckItemStatus.na : "fail" in value ? CheckItemStatus.fail : "pass" in value ? CheckItemStatus.pass : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fluid: null;
} | {
    tires: null;
} | {
    brakes: null;
} | {
    interior: null;
} | {
    body: null;
} | {
    lights: null;
} | {
    engine: null;
}): InspectionCategory {
    return "fluid" in value ? InspectionCategory.fluid : "tires" in value ? InspectionCategory.tires : "brakes" in value ? InspectionCategory.brakes : "interior" in value ? InspectionCategory.interior : "body" in value ? InspectionCategory.body : "lights" in value ? InspectionCategory.lights : "engine" in value ? InspectionCategory.engine : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    front: null;
} | {
    damage: null;
} | {
    rear: null;
} | {
    side: null;
}): PhotoCategory {
    return "front" in value ? PhotoCategory.front : "damage" in value ? PhotoCategory.damage : "rear" in value ? PhotoCategory.rear : "side" in value ? PhotoCategory.side : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inspection>): Promise<Array<Inspection>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Inspection_n28(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InspectionChecklistItem>): Array<InspectionChecklistItem> {
    return value.map((x)=>from_candid_InspectionChecklistItem_n33(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PhotoReference>): Promise<Array<PhotoReference>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PhotoReference_n40(_uploadFile, _downloadFile, x)));
}
function to_candid_CheckItemStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CheckItemStatus): _CheckItemStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_InspectionCategory_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InspectionCategory): _InspectionCategory {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_InspectionChecklistItem_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InspectionChecklistItem): _InspectionChecklistItem {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_InspectionStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InspectionStatus): _InspectionStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_Inspection_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Inspection): Promise<_Inspection> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_PhotoCategory_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PhotoCategory): _PhotoCategory {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function to_candid_PhotoReference_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PhotoReference): Promise<_PhotoReference> {
    return await to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: CheckItemStatus;
    item: string;
    notes: string;
    category: InspectionCategory;
}): {
    status: _CheckItemStatus;
    item: string;
    notes: string;
    category: _InspectionCategory;
} {
    return {
        status: to_candid_CheckItemStatus_n15(_uploadFile, _downloadFile, value.status),
        item: value.item,
        notes: value.notes,
        category: to_candid_InspectionCategory_n17(_uploadFile, _downloadFile, value.category)
    };
}
async function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: ExternalBlob;
    caption: string;
    category: PhotoCategory;
}): Promise<{
    blob: _ExternalBlob;
    caption: string;
    category: _PhotoCategory;
}> {
    return {
        blob: await to_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.blob),
        caption: value.caption,
        category: to_candid_PhotoCategory_n23(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: InspectionStatus;
    date: Time;
    checklistItems: Array<InspectionChecklistItem>;
    notes: string;
    inspectionId: string;
    overallStatus: CheckItemStatus;
    photos: Array<PhotoReference>;
    vehicleId: string;
    inspector: Principal;
}): Promise<{
    status: _InspectionStatus;
    date: _Time;
    checklistItems: Array<_InspectionChecklistItem>;
    notes: string;
    inspectionId: string;
    overallStatus: _CheckItemStatus;
    photos: Array<_PhotoReference>;
    vehicleId: string;
    inspector: Principal;
}> {
    return {
        status: to_candid_InspectionStatus_n10(_uploadFile, _downloadFile, value.status),
        date: value.date,
        checklistItems: to_candid_vec_n12(_uploadFile, _downloadFile, value.checklistItems),
        notes: value.notes,
        inspectionId: value.inspectionId,
        overallStatus: to_candid_CheckItemStatus_n15(_uploadFile, _downloadFile, value.overallStatus),
        photos: await to_candid_vec_n19(_uploadFile, _downloadFile, value.photos),
        vehicleId: value.vehicleId,
        inspector: value.inspector
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InspectionStatus): {
    completed: null;
} | {
    draft: null;
} | {
    inProgress: null;
} {
    return value == InspectionStatus.completed ? {
        completed: null
    } : value == InspectionStatus.draft ? {
        draft: null
    } : value == InspectionStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CheckItemStatus): {
    na: null;
} | {
    fail: null;
} | {
    pass: null;
} {
    return value == CheckItemStatus.na ? {
        na: null
    } : value == CheckItemStatus.fail ? {
        fail: null
    } : value == CheckItemStatus.pass ? {
        pass: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InspectionCategory): {
    fluid: null;
} | {
    tires: null;
} | {
    brakes: null;
} | {
    interior: null;
} | {
    body: null;
} | {
    lights: null;
} | {
    engine: null;
} {
    return value == InspectionCategory.fluid ? {
        fluid: null
    } : value == InspectionCategory.tires ? {
        tires: null
    } : value == InspectionCategory.brakes ? {
        brakes: null
    } : value == InspectionCategory.interior ? {
        interior: null
    } : value == InspectionCategory.body ? {
        body: null
    } : value == InspectionCategory.lights ? {
        lights: null
    } : value == InspectionCategory.engine ? {
        engine: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PhotoCategory): {
    front: null;
} | {
    damage: null;
} | {
    rear: null;
} | {
    side: null;
} {
    return value == PhotoCategory.front ? {
        front: null
    } : value == PhotoCategory.damage ? {
        damage: null
    } : value == PhotoCategory.rear ? {
        rear: null
    } : value == PhotoCategory.side ? {
        side: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<InspectionChecklistItem>): Array<_InspectionChecklistItem> {
    return value.map((x)=>to_candid_InspectionChecklistItem_n13(_uploadFile, _downloadFile, x));
}
async function to_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PhotoReference>): Promise<Array<_PhotoReference>> {
    return await Promise.all(value.map(async (x)=>await to_candid_PhotoReference_n20(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
